; PlatformIO Project Configuration File for Smart IV Drip Monitor
;
; Platform: ESP32 DevKit V1
; Framework: Arduino
; Libraries: Adafruit GFX, Adafruit ST7735

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
board_build.partitions = min_spiffs.csv
upload_speed = 921600
monitor_speed = 115200

lib_deps =
    adafruit/Adafruit GFX Library @ ^1.11.9
    adafruit/Adafruit ST7735 and ST7789 Library @ ^1.10.4
    SPI
    WiFi
    ArduinoOTA

; Optional OTA Environment - Uncomment/use this when deploying wirelessly
[env:esp32dev_ota]
extends = env:esp32dev
upload_protocol = espota
upload_port = DripCounter.local
upload_flags =
    --port=3232
